### ISSUE TITLE
Language bug causes preprocess failure

### ISSUE THREAD

**Issue by bondjimbond** [discoverygarden/islandora_paged_content_pdf_batch#16]
Preprocess fails with the following error:

> The specified language, eng, is not valid. Languages available are: .

Looks like there's a problem with the $valid_languages variable... which is weird, because I don't include the language parameter at all, and the code says that it's supposed to be optional.

**Comment by nhart** [comment]
@bondjimbond Please open a support ticket and we will investigate; we don't use github issues.

Cheers,
Nelson
