### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by bondjimbond** [discoverygarden/islandora_paged_content_pdf_batch#17]
Content model: parameter given is: 

> --content-model=xxx

which throws an error. Should be:

> --content_model=xxx

Namespace: This is parameter is required, but not documented in the example command.

Error if parameter is not included: 

> Missing required option: --namespace.

**Comment by nhart** [comment]
@bondjimbond Please open a support ticket and we will investigate; we don't use github issues.

Cheers,
Nelson
